version: "3"
services:
  db:
    image: postgres:14  # https://hub.docker.com/_/postgres
    restart: always
    ports:
      - "5432"
    volumes:
      - ./app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      # This optional variable can be used to define another location -
      # like a subdirectory - for the database files.
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      # This optional environment variable is used in conjunction with POSTGRES_PASSWORD
      # to set a user and its password. This variable will create the specified user with superuser
      # power and a database with the same name. If it is not specified, then the default user of
      # postgres will be used.
      - POSTGRES_USER=dev
      # This environment variable is required for you to use the PostgreSQL image.
      # It must not be empty or undefined. This environment variable sets the superuser
      # password for PostgreSQL. The default superuser is defined by the POSTGRES_USER environment variable.
      - POSTGRES_PASSWORD=ax2
      - POSTGRES_DB=app

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --reload-dir app --workers 1 --host 0.0.0.0 --port 8000 # --relaod ensures server will restart when changes are added to code base.
    # restart: always # reload is already set above.
    depends_on:
      - db
    ports:
      - "8008:8000"
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=postgresql://dev:ax2@db:5432/app
      # - DATABASE_TEST_URL=postgresql://postgres:password@db:5432/app_test
volumes:
  app-db-data:
